services:
  # AWS CLI containers for each account
  awscli-account1:
    build: .
    image: aws-security-hub-soc:latest
    container_name: aws-security-hub-account1
    volumes:
      - ./aws-credentials/account1:/root/.aws:ro
      - ./aws-scripts:/aws-scripts:ro
      - ./output/account1:/output
    working_dir: /aws-scripts
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - ACCOUNT_NAME=account1
    entrypoint: ["/bin/bash"]
    tty: true
    stdin_open: true
    networks:
      - aws-security-network

  awscli-account2:
    build: .
    image: aws-security-hub-soc:latest
    container_name: aws-security-hub-account2
    volumes:
      - ./aws-credentials/account2:/root/.aws:ro
      - ./aws-scripts:/aws-scripts:ro
      - ./output/account2:/output
    working_dir: /aws-scripts
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - ACCOUNT_NAME=account2
    entrypoint: ["/bin/bash"]
    tty: true
    stdin_open: true
    networks:
      - aws-security-network

  awscli-account3:
    build: .
    image: aws-security-hub-soc:latest
    container_name: aws-security-hub-account3
    volumes:
      - ./aws-credentials/account3:/root/.aws:ro
      - ./aws-scripts:/aws-scripts:ro
      - ./output/account3:/output
    working_dir: /aws-scripts
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - ACCOUNT_NAME=account3
    entrypoint: ["/bin/bash"]
    tty: true
    stdin_open: true
    networks:
      - aws-security-network

  security-hub-aggregator:
    build: .
    image: aws-security-hub-soc:latest
    container_name: aws-security-hub-aggregator
    volumes:
      - ./aws-credentials/master:/root/.aws:ro
      - ./aws-scripts:/aws-scripts:ro
      - ./output/aggregated:/output
    working_dir: /aws-scripts
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - ACCOUNT_NAME=master
    entrypoint: ["/bin/bash"]
    tty: true
    stdin_open: true
    networks:
      - aws-security-network

  # Flask Dashboard for Security Hub Findings
  security-dashboard:
    build: 
      context: .
      dockerfile: Dockerfile-dashboard
    container_name: aws-security-hub-dashboard
    ports:
      - "5001:5000"
    volumes:
      - ./output:/app/output:ro
      - ./app.py:/app/app.py:ro
      - ./templates:/app/templates:ro
    environment:
      - FLASK_ENV=development
    networks:
      - aws-security-network
    depends_on:
      - awscli-account1
      - awscli-account2
      - awscli-account3

networks:
  aws-security-network:
    driver: bridge
