apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 30s
      httpMethod: POST

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "security-hub-*"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 70
      maxConcurrentShardRequests: 5
      includeFrozen: false
      logMessageField: message
      logLevelField: level
    editable: true
